# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/soc/soc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc || ORIG_REF_NAME==soc} -quiet] -quiet

# IP: bd/soc/ip/soc_processing_system7_0_0/soc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_processing_system7_0_0 || ORIG_REF_NAME==soc_processing_system7_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_bram_ctrl_0_0/soc_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_bram_ctrl_0_0 || ORIG_REF_NAME==soc_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_smc_0/soc_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_smc_0 || ORIG_REF_NAME==soc_axi_smc_0} -quiet] -quiet

# IP: bd/soc/ip/soc_rst_ps7_0_50M_0/soc_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_rst_ps7_0_50M_0 || ORIG_REF_NAME==soc_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_bram_ctrl_0_bram_0/soc_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==soc_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/soc/ip/soc_c_shift_ram_0_0/soc_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_shift_ram_0_0 || ORIG_REF_NAME==soc_c_shift_ram_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_c_counter_binary_0_0/soc_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_counter_binary_0_0 || ORIG_REF_NAME==soc_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconstant_0_0/soc_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconstant_0_0 || ORIG_REF_NAME==soc_xlconstant_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_util_reduced_logic_0_0/soc_util_reduced_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_reduced_logic_0_0 || ORIG_REF_NAME==soc_util_reduced_logic_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_0_0/soc_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_0_0 || ORIG_REF_NAME==soc_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_util_reduced_logic_0_1/soc_util_reduced_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_reduced_logic_0_1 || ORIG_REF_NAME==soc_util_reduced_logic_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_0_1/soc_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_0_1 || ORIG_REF_NAME==soc_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_c_addsub_0_0/soc_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_addsub_0_0 || ORIG_REF_NAME==soc_c_addsub_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_0_0/soc_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_0_0 || ORIG_REF_NAME==soc_xlslice_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_0_2/soc_util_vector_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_0_2 || ORIG_REF_NAME==soc_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/soc/ip/soc_c_counter_binary_0_1/soc_c_counter_binary_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_counter_binary_0_1 || ORIG_REF_NAME==soc_c_counter_binary_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_0_1/soc_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_0_1 || ORIG_REF_NAME==soc_xlslice_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_0_2/soc_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_0_2 || ORIG_REF_NAME==soc_xlslice_0_2} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_1_0/soc_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_1_0 || ORIG_REF_NAME==soc_xlslice_1_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_1_1/soc_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_1_1 || ORIG_REF_NAME==soc_xlslice_1_1} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_0_3/soc_util_vector_logic_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_0_3 || ORIG_REF_NAME==soc_util_vector_logic_0_3} -quiet] -quiet

# IP: bd/soc/ip/soc_n_x_0_0/soc_n_x_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_n_x_0_0 || ORIG_REF_NAME==soc_n_x_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_n_x_0_1/soc_n_x_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_n_x_0_1 || ORIG_REF_NAME==soc_n_x_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_n_x_0_2/soc_n_x_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_n_x_0_2 || ORIG_REF_NAME==soc_n_x_0_2} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_0_0/soc_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_0_0 || ORIG_REF_NAME==soc_xlconcat_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_util_reduced_logic_0_2/soc_util_reduced_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_reduced_logic_0_2 || ORIG_REF_NAME==soc_util_reduced_logic_0_2} -quiet] -quiet

# IP: bd/soc/ip/soc_c_0_0/soc_c_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_0_0 || ORIG_REF_NAME==soc_c_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_s_0_0/soc_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_s_0_0 || ORIG_REF_NAME==soc_s_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_c_1_1/soc_c_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_1_1 || ORIG_REF_NAME==soc_c_1_1} -quiet] -quiet

# IP: bd/soc/ip/soc_s_1_1/soc_s_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_s_1_1 || ORIG_REF_NAME==soc_s_1_1} -quiet] -quiet

# IP: bd/soc/ip/soc_c_2_0/soc_c_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_2_0 || ORIG_REF_NAME==soc_c_2_0} -quiet] -quiet

# IP: bd/soc/ip/soc_s_2_0/soc_s_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_s_2_0 || ORIG_REF_NAME==soc_s_2_0} -quiet] -quiet

# IP: bd/soc/ip/soc_c_3_0/soc_c_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_3_0 || ORIG_REF_NAME==soc_c_3_0} -quiet] -quiet

# IP: bd/soc/ip/soc_s_3_0/soc_s_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_s_3_0 || ORIG_REF_NAME==soc_s_3_0} -quiet] -quiet

# IP: bd/soc/ip/soc_c_4_0/soc_c_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_4_0 || ORIG_REF_NAME==soc_c_4_0} -quiet] -quiet

# IP: bd/soc/ip/soc_s_4_0/soc_s_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_s_4_0 || ORIG_REF_NAME==soc_s_4_0} -quiet] -quiet

# IP: bd/soc/ip/soc_c_5_0/soc_c_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_5_0 || ORIG_REF_NAME==soc_c_5_0} -quiet] -quiet

# IP: bd/soc/ip/soc_s_5_0/soc_s_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_s_5_0 || ORIG_REF_NAME==soc_s_5_0} -quiet] -quiet

# IP: bd/soc/ip/soc_c_6_0/soc_c_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_6_0 || ORIG_REF_NAME==soc_c_6_0} -quiet] -quiet

# IP: bd/soc/ip/soc_s_6_0/soc_s_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_s_6_0 || ORIG_REF_NAME==soc_s_6_0} -quiet] -quiet

# IP: bd/soc/ip/soc_c_7_0/soc_c_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_7_0 || ORIG_REF_NAME==soc_c_7_0} -quiet] -quiet

# IP: bd/soc/ip/soc_s_4_1/soc_s_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_s_4_1 || ORIG_REF_NAME==soc_s_4_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_0_2/soc_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_0_2 || ORIG_REF_NAME==soc_xlconcat_0_2} -quiet] -quiet

# IP: bd/soc/ip/soc_util_reduced_logic_0_3/soc_util_reduced_logic_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_reduced_logic_0_3 || ORIG_REF_NAME==soc_util_reduced_logic_0_3} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_0_4/soc_util_vector_logic_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_0_4 || ORIG_REF_NAME==soc_util_vector_logic_0_4} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_0_5/soc_util_vector_logic_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_0_5 || ORIG_REF_NAME==soc_util_vector_logic_0_5} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_1_0/soc_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_1_0 || ORIG_REF_NAME==soc_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_2_0/soc_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_2_0 || ORIG_REF_NAME==soc_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_3_0/soc_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_3_0 || ORIG_REF_NAME==soc_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/soc/ip/soc_div_gen_0_0/soc_div_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_div_gen_0_0 || ORIG_REF_NAME==soc_div_gen_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_0_3/soc_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_0_3 || ORIG_REF_NAME==soc_xlslice_0_3} -quiet] -quiet

# IP: bd/soc/ip/soc_c_shift_ram_0_2/soc_c_shift_ram_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_shift_ram_0_2 || ORIG_REF_NAME==soc_c_shift_ram_0_2} -quiet] -quiet

# IP: bd/soc/ip/soc_cordic_0_0/soc_cordic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_cordic_0_0 || ORIG_REF_NAME==soc_cordic_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_c_counter_binary_0_2/soc_c_counter_binary_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_counter_binary_0_2 || ORIG_REF_NAME==soc_c_counter_binary_0_2} -quiet] -quiet

# IP: bd/soc/ip/soc_c_shift_ram_0_3/soc_c_shift_ram_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_shift_ram_0_3 || ORIG_REF_NAME==soc_c_shift_ram_0_3} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_0_4/soc_xlslice_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_0_4 || ORIG_REF_NAME==soc_xlslice_0_4} -quiet] -quiet

# IP: bd/soc/ip/soc_x_0_0/soc_x_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_x_0_0 || ORIG_REF_NAME==soc_x_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_0_7/soc_util_vector_logic_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_0_7 || ORIG_REF_NAME==soc_util_vector_logic_0_7} -quiet] -quiet

# IP: bd/soc/ip/soc_n_x_0_3/soc_n_x_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_n_x_0_3 || ORIG_REF_NAME==soc_n_x_0_3} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_0_8/soc_util_vector_logic_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_0_8 || ORIG_REF_NAME==soc_util_vector_logic_0_8} -quiet] -quiet

# IP: bd/soc/ip/soc_s_0_1/soc_s_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_s_0_1 || ORIG_REF_NAME==soc_s_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_s_0_2/soc_s_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_s_0_2 || ORIG_REF_NAME==soc_s_0_2} -quiet] -quiet

# IP: bd/soc/ip/soc_s_0_3/soc_s_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_s_0_3 || ORIG_REF_NAME==soc_s_0_3} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_0_4/soc_xlconcat_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_0_4 || ORIG_REF_NAME==soc_xlconcat_0_4} -quiet] -quiet

# IP: bd/soc/ip/soc_util_reduced_logic_0_5/soc_util_reduced_logic_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_reduced_logic_0_5 || ORIG_REF_NAME==soc_util_reduced_logic_0_5} -quiet] -quiet

# IP: bd/soc/ip/soc_s_3_1/soc_s_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_s_3_1 || ORIG_REF_NAME==soc_s_3_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xbip_dsp48_macro_0_0/soc_xbip_dsp48_macro_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xbip_dsp48_macro_0_0 || ORIG_REF_NAME==soc_xbip_dsp48_macro_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_gpio_0_0/soc_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_gpio_0_0 || ORIG_REF_NAME==soc_axi_gpio_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_gpio_0_1/soc_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_gpio_0_1 || ORIG_REF_NAME==soc_axi_gpio_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_1_2/soc_xlslice_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_1_2 || ORIG_REF_NAME==soc_xlslice_1_2} -quiet] -quiet

# IP: bd/soc/ip/soc_xbip_dsp48_macro_1_0/soc_xbip_dsp48_macro_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xbip_dsp48_macro_1_0 || ORIG_REF_NAME==soc_xbip_dsp48_macro_1_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xbip_dsp48_macro_2_0/soc_xbip_dsp48_macro_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xbip_dsp48_macro_2_0 || ORIG_REF_NAME==soc_xbip_dsp48_macro_2_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_2_0/soc_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_2_0 || ORIG_REF_NAME==soc_xlslice_2_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_1_1/soc_xlconcat_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_1_1 || ORIG_REF_NAME==soc_xlconcat_1_1} -quiet] -quiet

# IP: bd/soc/ip/soc_b_0_0/soc_b_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_b_0_0 || ORIG_REF_NAME==soc_b_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_1_2/soc_xlconcat_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_1_2 || ORIG_REF_NAME==soc_xlconcat_1_2} -quiet] -quiet

# IP: bd/soc/ip/soc_b_1_0/soc_b_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_b_1_0 || ORIG_REF_NAME==soc_b_1_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_2_0/soc_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_2_0 || ORIG_REF_NAME==soc_xlconcat_2_0} -quiet] -quiet

# IP: bd/soc/ip/soc_b_2_0/soc_b_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_b_2_0 || ORIG_REF_NAME==soc_b_2_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_3_0/soc_xlconcat_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_3_0 || ORIG_REF_NAME==soc_xlconcat_3_0} -quiet] -quiet

# IP: bd/soc/ip/soc_c_addsub_0_2/soc_c_addsub_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_addsub_0_2 || ORIG_REF_NAME==soc_c_addsub_0_2} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_3_0/soc_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_3_0 || ORIG_REF_NAME==soc_xlslice_3_0} -quiet] -quiet

# IP: bd/soc/ip/soc_util_reduced_logic_0_4/soc_util_reduced_logic_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_reduced_logic_0_4 || ORIG_REF_NAME==soc_util_reduced_logic_0_4} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_0_6/soc_util_vector_logic_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_0_6 || ORIG_REF_NAME==soc_util_vector_logic_0_6} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_gpio_1_0/soc_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_gpio_1_0 || ORIG_REF_NAME==soc_axi_gpio_1_0} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_1_1/soc_util_vector_logic_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_1_1 || ORIG_REF_NAME==soc_util_vector_logic_1_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_0_1/soc_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_0_1 || ORIG_REF_NAME==soc_xlconcat_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_3_1/soc_util_vector_logic_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_3_1 || ORIG_REF_NAME==soc_util_vector_logic_3_1} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_bram_ctrl_0_1/soc_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_bram_ctrl_0_1 || ORIG_REF_NAME==soc_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_div_gen_0_1/soc_div_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_div_gen_0_1 || ORIG_REF_NAME==soc_div_gen_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_0_7/soc_xlslice_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_0_7 || ORIG_REF_NAME==soc_xlslice_0_7} -quiet] -quiet

# IP: bd/soc/ip/soc_c_shift_ram_0_1/soc_c_shift_ram_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_shift_ram_0_1 || ORIG_REF_NAME==soc_c_shift_ram_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconstant_0_5/soc_xlconstant_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconstant_0_5 || ORIG_REF_NAME==soc_xlconstant_0_5} -quiet] -quiet

# IP: bd/soc/ip/soc_xbip_dsp48_macro_0_1/soc_xbip_dsp48_macro_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xbip_dsp48_macro_0_1 || ORIG_REF_NAME==soc_xbip_dsp48_macro_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xbip_dsp48_macro_1_1/soc_xbip_dsp48_macro_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xbip_dsp48_macro_1_1 || ORIG_REF_NAME==soc_xbip_dsp48_macro_1_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xbip_dsp48_macro_2_1/soc_xbip_dsp48_macro_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xbip_dsp48_macro_2_1 || ORIG_REF_NAME==soc_xbip_dsp48_macro_2_1} -quiet] -quiet

# IP: bd/soc/ip/soc_b_0_1/soc_b_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_b_0_1 || ORIG_REF_NAME==soc_b_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_1_0/soc_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_1_0 || ORIG_REF_NAME==soc_xlconcat_1_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconstant_2_1/soc_xlconstant_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconstant_2_1 || ORIG_REF_NAME==soc_xlconstant_2_1} -quiet] -quiet

# IP: bd/soc/ip/soc_b_1_1/soc_b_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_b_1_1 || ORIG_REF_NAME==soc_b_1_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_2_1/soc_xlconcat_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_2_1 || ORIG_REF_NAME==soc_xlconcat_2_1} -quiet] -quiet

# IP: bd/soc/ip/soc_b_2_1/soc_b_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_b_2_1 || ORIG_REF_NAME==soc_b_2_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_3_1/soc_xlconcat_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_3_1 || ORIG_REF_NAME==soc_xlconcat_3_1} -quiet] -quiet

# IP: bd/soc/ip/soc_b_3_0/soc_b_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_b_3_0 || ORIG_REF_NAME==soc_b_3_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_4_0/soc_xlconcat_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_4_0 || ORIG_REF_NAME==soc_xlconcat_4_0} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_bram_ctrl_0_bram_1/soc_axi_bram_ctrl_0_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_bram_ctrl_0_bram_1 || ORIG_REF_NAME==soc_axi_bram_ctrl_0_bram_1} -quiet] -quiet

# IP: bd/soc/ip/soc_clk_wiz_0_0/soc_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_clk_wiz_0_0 || ORIG_REF_NAME==soc_clk_wiz_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xbip_dsp48_macro_0_2/soc_xbip_dsp48_macro_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xbip_dsp48_macro_0_2 || ORIG_REF_NAME==soc_xbip_dsp48_macro_0_2} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_0_11/soc_util_vector_logic_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_0_11 || ORIG_REF_NAME==soc_util_vector_logic_0_11} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_0_12/soc_util_vector_logic_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_0_12 || ORIG_REF_NAME==soc_util_vector_logic_0_12} -quiet] -quiet

# IP: bd/soc/ip/soc_cordic_0_1/soc_cordic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_cordic_0_1 || ORIG_REF_NAME==soc_cordic_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_0_10/soc_xlslice_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_0_10 || ORIG_REF_NAME==soc_xlslice_0_10} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_0_11/soc_xlslice_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_0_11 || ORIG_REF_NAME==soc_xlslice_0_11} -quiet] -quiet

# IP: bd/soc/ip/soc_mult_gen_0_0/soc_mult_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_mult_gen_0_0 || ORIG_REF_NAME==soc_mult_gen_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_0_3/soc_xlconcat_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_0_3 || ORIG_REF_NAME==soc_xlconcat_0_3} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconstant_0_7/soc_xlconstant_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconstant_0_7 || ORIG_REF_NAME==soc_xlconstant_0_7} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_5_0/soc_util_vector_logic_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_5_0 || ORIG_REF_NAME==soc_util_vector_logic_5_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_0_5/soc_xlslice_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_0_5 || ORIG_REF_NAME==soc_xlslice_0_5} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_0_5/soc_xlconcat_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_0_5 || ORIG_REF_NAME==soc_xlconcat_0_5} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconstant_0_1/soc_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconstant_0_1 || ORIG_REF_NAME==soc_xlconstant_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_0_6/soc_xlconcat_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_0_6 || ORIG_REF_NAME==soc_xlconcat_0_6} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_0_6/soc_xlslice_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_0_6 || ORIG_REF_NAME==soc_xlslice_0_6} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconstant_0_2/soc_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconstant_0_2 || ORIG_REF_NAME==soc_xlconstant_0_2} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_0_7/soc_xlconcat_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_0_7 || ORIG_REF_NAME==soc_xlconcat_0_7} -quiet] -quiet

# IP: bd/soc/ip/soc_util_reduced_logic_1_0/soc_util_reduced_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_reduced_logic_1_0 || ORIG_REF_NAME==soc_util_reduced_logic_1_0} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_1_2/soc_util_vector_logic_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_1_2 || ORIG_REF_NAME==soc_util_vector_logic_1_2} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_7_0/soc_xlslice_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_7_0 || ORIG_REF_NAME==soc_xlslice_7_0} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_1_3/soc_util_vector_logic_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_1_3 || ORIG_REF_NAME==soc_util_vector_logic_1_3} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconstant_0_3/soc_xlconstant_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconstant_0_3 || ORIG_REF_NAME==soc_xlconstant_0_3} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_bram_ctrl_1_0/soc_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_bram_ctrl_1_0 || ORIG_REF_NAME==soc_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/soc/ip/soc_axi_bram_ctrl_2_bram_0/soc_axi_bram_ctrl_2_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_axi_bram_ctrl_2_bram_0 || ORIG_REF_NAME==soc_axi_bram_ctrl_2_bram_0} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_0_8/soc_xlconcat_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_0_8 || ORIG_REF_NAME==soc_xlconcat_0_8} -quiet] -quiet

# IP: bd/soc/ip/soc_c_counter_binary_0_3/soc_c_counter_binary_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_counter_binary_0_3 || ORIG_REF_NAME==soc_c_counter_binary_0_3} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_1_4/soc_util_vector_logic_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_1_4 || ORIG_REF_NAME==soc_util_vector_logic_1_4} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_0_9/soc_util_vector_logic_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_0_9 || ORIG_REF_NAME==soc_util_vector_logic_0_9} -quiet] -quiet

# IP: bd/soc/ip/soc_util_reduced_logic_0_6/soc_util_reduced_logic_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_reduced_logic_0_6 || ORIG_REF_NAME==soc_util_reduced_logic_0_6} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_1_5/soc_util_vector_logic_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_1_5 || ORIG_REF_NAME==soc_util_vector_logic_1_5} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_1_6/soc_util_vector_logic_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_1_6 || ORIG_REF_NAME==soc_util_vector_logic_1_6} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_0_10/soc_util_vector_logic_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_0_10 || ORIG_REF_NAME==soc_util_vector_logic_0_10} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_7_0/soc_util_vector_logic_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_7_0 || ORIG_REF_NAME==soc_util_vector_logic_7_0} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_0_13/soc_util_vector_logic_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_0_13 || ORIG_REF_NAME==soc_util_vector_logic_0_13} -quiet] -quiet

# IP: bd/soc/ip/soc_c_shift_ram_0_5/soc_c_shift_ram_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_shift_ram_0_5 || ORIG_REF_NAME==soc_c_shift_ram_0_5} -quiet] -quiet

# IP: bd/soc/ip/soc_c_shift_ram_0_8/soc_c_shift_ram_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_shift_ram_0_8 || ORIG_REF_NAME==soc_c_shift_ram_0_8} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_0_14/soc_util_vector_logic_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_0_14 || ORIG_REF_NAME==soc_util_vector_logic_0_14} -quiet] -quiet

# IP: bd/soc/ip/soc_c_addsub_0_1/soc_c_addsub_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_addsub_0_1 || ORIG_REF_NAME==soc_c_addsub_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_0_8/soc_xlslice_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_0_8 || ORIG_REF_NAME==soc_xlslice_0_8} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_0_9/soc_xlconcat_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_0_9 || ORIG_REF_NAME==soc_xlconcat_0_9} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconstant_0_4/soc_xlconstant_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconstant_0_4 || ORIG_REF_NAME==soc_xlconstant_0_4} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_0_13/soc_xlslice_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_0_13 || ORIG_REF_NAME==soc_xlslice_0_13} -quiet] -quiet

# IP: bd/soc/ip/soc_c_shift_ram_0_7/soc_c_shift_ram_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_c_shift_ram_0_7 || ORIG_REF_NAME==soc_c_shift_ram_0_7} -quiet] -quiet

# IP: bd/soc/ip/soc_div_gen_0_3/soc_div_gen_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_div_gen_0_3 || ORIG_REF_NAME==soc_div_gen_0_3} -quiet] -quiet

# IP: bd/soc/ip/soc_xlslice_1_3/soc_xlslice_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlslice_1_3 || ORIG_REF_NAME==soc_xlslice_1_3} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_0_10/soc_xlconcat_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_0_10 || ORIG_REF_NAME==soc_xlconcat_0_10} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconstant_0_8/soc_xlconstant_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconstant_0_8 || ORIG_REF_NAME==soc_xlconstant_0_8} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_1_7/soc_util_vector_logic_1_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_1_7 || ORIG_REF_NAME==soc_util_vector_logic_1_7} -quiet] -quiet

# IP: bd/soc/ip/soc_util_reduced_logic_0_7/soc_util_reduced_logic_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_reduced_logic_0_7 || ORIG_REF_NAME==soc_util_reduced_logic_0_7} -quiet] -quiet

# IP: bd/soc/ip/soc_util_vector_logic_2_1/soc_util_vector_logic_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_util_vector_logic_2_1 || ORIG_REF_NAME==soc_util_vector_logic_2_1} -quiet] -quiet

# XDC: bd/soc/soc_ooc.xdc
