# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/dell_/bram_comm_2/bram_comm_2.cache/wt [current_project]
set_property parent.project_path C:/Users/dell_/bram_comm_2/bram_comm_2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zc706:part0:1.4 [current_project]
set_property ip_output_repo c:/Users/dell_/bram_comm_2/bram_comm_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/hdl/soc_wrapper.vhd
add_files C:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/soc.bd
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_processing_system7_0_0/soc_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_bram_ctrl_0_0/soc_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_10/bd_776a_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_16/bd_776a_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_23/bd_776a_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_30/bd_776a_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_37/bd_776a_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_44/bd_776a_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_51/bd_776a_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_52/bd_776a_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_53/bd_776a_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_54/bd_776a_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_55/bd_776a_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_56/bd_776a_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_45/bd_776a_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_46/bd_776a_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_47/bd_776a_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_48/bd_776a_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_49/bd_776a_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_38/bd_776a_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_39/bd_776a_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_40/bd_776a_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_41/bd_776a_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_42/bd_776a_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_31/bd_776a_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_32/bd_776a_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_33/bd_776a_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_34/bd_776a_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_35/bd_776a_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_24/bd_776a_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_25/bd_776a_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_26/bd_776a_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_27/bd_776a_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_28/bd_776a_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_17/bd_776a_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_18/bd_776a_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_19/bd_776a_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_20/bd_776a_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_21/bd_776a_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_11/bd_776a_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_12/bd_776a_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_13/bd_776a_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_14/bd_776a_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_15/bd_776a_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_2/bd_776a_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_3/bd_776a_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_4/bd_776a_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_5/bd_776a_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_6/bd_776a_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_1/bd_776a_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_1/bd_776a_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_rst_ps7_0_50M_0/soc_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_rst_ps7_0_50M_0/soc_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_rst_ps7_0_50M_0/soc_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_bram_ctrl_0_bram_0/soc_axi_bram_ctrl_0_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_c_shift_ram_0_0/soc_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_c_counter_binary_0_0/soc_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_c_counter_binary_0_1/soc_c_counter_binary_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_div_gen_0_0/soc_div_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_c_shift_ram_0_2/soc_c_shift_ram_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_cordic_0_0/soc_cordic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_c_counter_binary_0_2/soc_c_counter_binary_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_c_shift_ram_0_3/soc_c_shift_ram_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_xbip_dsp48_macro_0_0/soc_xbip_dsp48_macro_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_gpio_0_0/soc_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_gpio_0_0/soc_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_gpio_0_0/soc_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_gpio_0_1/soc_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_gpio_0_1/soc_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_gpio_0_1/soc_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_gpio_1_0/soc_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_gpio_1_0/soc_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_gpio_1_0/soc_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_bram_ctrl_0_1/soc_axi_bram_ctrl_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_div_gen_0_1/soc_div_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_c_shift_ram_0_1/soc_c_shift_ram_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_xbip_dsp48_macro_0_1/soc_xbip_dsp48_macro_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_bram_ctrl_0_bram_1/soc_axi_bram_ctrl_0_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_clk_wiz_0_0/soc_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_clk_wiz_0_0/soc_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_clk_wiz_0_0/soc_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_xbip_dsp48_macro_0_2/soc_xbip_dsp48_macro_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_cordic_0_1/soc_cordic_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_div_gen_0_3/soc_div_gen_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_c_shift_ram_0_4/soc_c_shift_ram_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_bram_ctrl_1_0/soc_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_axi_bram_ctrl_2_bram_0/soc_axi_bram_ctrl_2_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_c_counter_binary_0_3/soc_c_counter_binary_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/dell_/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/soc_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top soc_wrapper -part xc7z045ffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_wrapper_utilization_synth.rpt -pb soc_wrapper_utilization_synth.pb"
