#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2017.3 (64-bit)
#
# Filename    : soc.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Mar 20 16:56:57 -0600 2021
# SW Build 2018833 on Wed Oct  4 19:58:22 MDT 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved. 
#
# usage: soc.sh [-help]
# usage: soc.sh [-lib_map_path]
# usage: soc.sh [-noclean_files]
# usage: soc.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'soc.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_0 axi_vip_v1_1_0 processing_system7_vip_v1_0_2 blk_mem_gen_v8_3_6 axi_bram_ctrl_v4_0_12 xlconstant_v1_1_3 lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 blk_mem_gen_v8_4_0 xbip_utils_v3_0_8 c_reg_fd_v12_0_4 c_mux_bit_v12_0_4 c_shift_ram_v12_0_11 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_4 xbip_dsp48_addsub_v3_0_4 xbip_addsub_v3_0_4 c_addsub_v12_0_11 c_gate_bit_v12_0_4 xbip_counter_v3_0_4 c_counter_binary_v12_0_11 util_reduced_logic_v2_0_3 util_vector_logic_v2_0_1 xlslice_v1_0_1 xlconcat_v2_1_1 axi_utils_v2_0_4 xbip_bram18k_v3_0_4 mult_gen_v12_0_13 floating_point_v7_0_14 xbip_dsp48_mult_v3_0_4 xbip_dsp48_multadd_v3_0_4 div_gen_v5_1_12 cordic_v6_0_12 xbip_dsp48_macro_v3_0_15 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_16)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "soc.sh - Script generated by export_simulation (Vivado v2017.3 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5c1/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/8b42/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_2 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_processing_system7_0_0/sim/soc_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_3_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/2751/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_0_12 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ffa3/hdl/axi_bram_ctrl_v4_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_axi_bram_ctrl_0_0/sim/soc_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/sim/bd_776a.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/786b/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_10/sim/bd_776a_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/92d2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_16/sim/bd_776a_m00s2a_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_23/sim/bd_776a_m01s2a_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_30/sim/bd_776a_m02s2a_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_37/sim/bd_776a_m03s2a_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_44/sim/bd_776a_m04s2a_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_51/sim/bd_776a_m05s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/fa70/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_57/sim/bd_776a_m05e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_52/sim/bd_776a_m05arn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_53/sim/bd_776a_m05rn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_54/sim/bd_776a_m05awn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_55/sim/bd_776a_m05wn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_56/sim/bd_776a_m05bn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_50/sim/bd_776a_m04e_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_45/sim/bd_776a_m04arn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_46/sim/bd_776a_m04rn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_47/sim/bd_776a_m04awn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_48/sim/bd_776a_m04wn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_49/sim/bd_776a_m04bn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_43/sim/bd_776a_m03e_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_38/sim/bd_776a_m03arn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_39/sim/bd_776a_m03rn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_40/sim/bd_776a_m03awn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_41/sim/bd_776a_m03wn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_42/sim/bd_776a_m03bn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_36/sim/bd_776a_m02e_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_31/sim/bd_776a_m02arn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_32/sim/bd_776a_m02rn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_33/sim/bd_776a_m02awn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_34/sim/bd_776a_m02wn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_35/sim/bd_776a_m02bn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_29/sim/bd_776a_m01e_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_24/sim/bd_776a_m01arn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_25/sim/bd_776a_m01rn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_26/sim/bd_776a_m01awn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_27/sim/bd_776a_m01wn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_28/sim/bd_776a_m01bn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_22/sim/bd_776a_m00e_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_17/sim/bd_776a_m00arn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_18/sim/bd_776a_m00rn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_19/sim/bd_776a_m00awn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_20/sim/bd_776a_m00wn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_21/sim/bd_776a_m00bn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_11/sim/bd_776a_sarn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_12/sim/bd_776a_srn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_13/sim/bd_776a_sawn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_14/sim/bd_776a_swn_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_15/sim/bd_776a_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/8ad6/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_7/sim/bd_776a_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/0f5f/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_8/sim/bd_776a_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/925a/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_9/sim/bd_776a_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/1b0c/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_2/sim/bd_776a_arsw_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_3/sim/bd_776a_rsw_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_4/sim/bd_776a_awsw_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_5/sim/bd_776a_wsw_0.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_6/sim/bd_776a_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_0/sim/bd_776a_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/bd_0/ip/ip_1/sim/bd_776a_psr_aclk_0.vhd" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_smc_0/sim/soc_axi_smc_0.vhd" \
    "$ref_dir/../../../bd/soc/ip/soc_rst_ps7_0_50M_0/sim/soc_rst_ps7_0_50M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e50b/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_bram_ctrl_0_bram_0/sim/soc_axi_bram_ctrl_0_bram_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_8 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/4173/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_4 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e6f0/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_4 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/660b/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_11 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/7c1c/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_c_shift_ram_0_0/sim/soc_c_shift_ram_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/da55/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ee5e/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/7b8d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/c060/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_11 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/1607/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_4 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/4b95/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/df83/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_11 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ffc8/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_c_counter_binary_0_0/sim/soc_c_counter_binary_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconstant_0_0/sim/soc_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_reduced_logic_v2_0_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5006/hdl/util_reduced_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_util_reduced_logic_0_0/sim/soc_util_reduced_logic_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_0_0/sim/soc_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_reduced_logic_0_1/sim/soc_util_reduced_logic_0_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_0_1/sim/soc_util_vector_logic_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_c_addsub_0_0/sim/soc_c_addsub_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/f3db/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_0_0/sim/soc_xlslice_0_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_0_2/sim/soc_util_vector_logic_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_c_counter_binary_0_1/sim/soc_c_counter_binary_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_0_1/sim/soc_xlslice_0_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_0_2/sim/soc_xlslice_0_2.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_1_0/sim/soc_xlslice_1_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_1_1/sim/soc_xlslice_1_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_0_3/sim/soc_util_vector_logic_0_3.v" \
    "$ref_dir/../../../bd/soc/ip/soc_n_x_0_0/sim/soc_n_x_0_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_n_x_0_1/sim/soc_n_x_0_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_n_x_0_2/sim/soc_n_x_0_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_0_0/sim/soc_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_reduced_logic_0_2/sim/soc_util_reduced_logic_0_2.v" \
    "$ref_dir/../../../bd/soc/ip/soc_c_0_0/sim/soc_c_0_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_s_0_0/sim/soc_s_0_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_c_1_1/sim/soc_c_1_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_s_1_1/sim/soc_s_1_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_c_2_0/sim/soc_c_2_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_s_2_0/sim/soc_s_2_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_c_3_0/sim/soc_c_3_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_s_3_0/sim/soc_s_3_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_c_4_0/sim/soc_c_4_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_s_4_0/sim/soc_s_4_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_c_5_0/sim/soc_c_5_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_s_5_0/sim/soc_s_5_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_c_6_0/sim/soc_c_6_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_s_6_0/sim/soc_s_6_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_c_7_0/sim/soc_c_7_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_s_4_1/sim/soc_s_4_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_0_2/sim/soc_xlconcat_0_2.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_reduced_logic_0_3/sim/soc_util_reduced_logic_0_3.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_0_4/sim/soc_util_vector_logic_0_4.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_0_5/sim/soc_util_vector_logic_0_5.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_1_0/sim/soc_util_vector_logic_1_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_2_0/sim/soc_util_vector_logic_2_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_3_0/sim/soc_util_vector_logic_3_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_utils_v2_0_4 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/4575/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/9eb4/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_13 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/257f/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_0_14 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/6041/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_mult_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ea91/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/65ba/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work div_gen_v5_1_12 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/9ece/hdl/div_gen_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_div_gen_0_0/sim/soc_div_gen_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_0_3/sim/soc_xlslice_0_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_c_shift_ram_0_2/sim/soc_c_shift_ram_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cordic_v6_0_12 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/36ff/hdl/cordic_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_cordic_0_0/sim/soc_cordic_0_0.vhd" \
    "$ref_dir/../../../bd/soc/ip/soc_c_counter_binary_0_2/sim/soc_c_counter_binary_0_2.vhd" \
    "$ref_dir/../../../bd/soc/ip/soc_c_shift_ram_0_3/sim/soc_c_shift_ram_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_0_4/sim/soc_xlslice_0_4.v" \
    "$ref_dir/../../../bd/soc/ip/soc_x_0_0/sim/soc_x_0_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_0_7/sim/soc_util_vector_logic_0_7.v" \
    "$ref_dir/../../../bd/soc/ip/soc_n_x_0_3/sim/soc_n_x_0_3.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_0_8/sim/soc_util_vector_logic_0_8.v" \
    "$ref_dir/../../../bd/soc/ip/soc_s_0_1/sim/soc_s_0_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_s_0_2/sim/soc_s_0_2.v" \
    "$ref_dir/../../../bd/soc/ip/soc_s_0_3/sim/soc_s_0_3.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_0_4/sim/soc_xlconcat_0_4.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_reduced_logic_0_5/sim/soc_util_reduced_logic_0_5.v" \
    "$ref_dir/../../../bd/soc/ip/soc_s_3_1/sim/soc_s_3_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_dsp48_macro_v3_0_15 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/c423/hdl/xbip_dsp48_macro_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_xbip_dsp48_macro_0_0/sim/soc_xbip_dsp48_macro_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_16 $vhdlan_opts \
    "$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e9c1/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_axi_gpio_0_0/sim/soc_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_gpio_0_1/sim/soc_axi_gpio_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_1_2/sim/soc_xlslice_1_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_xbip_dsp48_macro_1_0/sim/soc_xbip_dsp48_macro_1_0.vhd" \
    "$ref_dir/../../../bd/soc/ip/soc_xbip_dsp48_macro_2_0/sim/soc_xbip_dsp48_macro_2_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_2_0/sim/soc_xlslice_2_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_1_1/sim/soc_xlconcat_1_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_b_0_0/sim/soc_b_0_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_1_2/sim/soc_xlconcat_1_2.v" \
    "$ref_dir/../../../bd/soc/ip/soc_b_1_0/sim/soc_b_1_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_2_0/sim/soc_xlconcat_2_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_b_2_0/sim/soc_b_2_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_3_0/sim/soc_xlconcat_3_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_c_addsub_0_2/sim/soc_c_addsub_0_2.vhd" \
    "$ref_dir/../../../bd/soc/sim/soc.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_3_0/sim/soc_xlslice_3_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_reduced_logic_0_4/sim/soc_util_reduced_logic_0_4.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_0_6/sim/soc_util_vector_logic_0_6.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_axi_gpio_1_0/sim/soc_axi_gpio_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_1_1/sim/soc_util_vector_logic_1_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_0_1/sim/soc_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_3_1/sim/soc_util_vector_logic_3_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_axi_bram_ctrl_0_1/sim/soc_axi_bram_ctrl_0_1.vhd" \
    "$ref_dir/../../../bd/soc/ip/soc_div_gen_0_1/sim/soc_div_gen_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_0_7/sim/soc_xlslice_0_7.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_c_shift_ram_0_1/sim/soc_c_shift_ram_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconstant_0_5/sim/soc_xlconstant_0_5.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_xbip_dsp48_macro_0_1/sim/soc_xbip_dsp48_macro_0_1.vhd" \
    "$ref_dir/../../../bd/soc/ip/soc_xbip_dsp48_macro_1_1/sim/soc_xbip_dsp48_macro_1_1.vhd" \
    "$ref_dir/../../../bd/soc/ip/soc_xbip_dsp48_macro_2_1/sim/soc_xbip_dsp48_macro_2_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_b_0_1/sim/soc_b_0_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_1_0/sim/soc_xlconcat_1_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconstant_2_1/sim/soc_xlconstant_2_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_b_1_1/sim/soc_b_1_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_2_1/sim/soc_xlconcat_2_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_b_2_1/sim/soc_b_2_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_3_1/sim/soc_xlconcat_3_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_b_3_0/sim/soc_b_3_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_4_0/sim/soc_xlconcat_4_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_bram_ctrl_0_bram_1/sim/soc_axi_bram_ctrl_0_bram_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_clk_wiz_0_0/soc_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/soc/ip/soc_clk_wiz_0_0/soc_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_xbip_dsp48_macro_0_2/sim/soc_xbip_dsp48_macro_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_0_11/sim/soc_util_vector_logic_0_11.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_0_12/sim/soc_util_vector_logic_0_12.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_cordic_0_1/sim/soc_cordic_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_0_10/sim/soc_xlslice_0_10.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_0_11/sim/soc_xlslice_0_11.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_mult_gen_0_0/sim/soc_mult_gen_0_0.vhd" \
    "$ref_dir/../../../bd/soc/ip/soc_div_gen_0_3/sim/soc_div_gen_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_0_3/sim/soc_xlconcat_0_3.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconstant_0_7/sim/soc_xlconstant_0_7.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_0_12/sim/soc_xlslice_0_12.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_5_0/sim/soc_util_vector_logic_5_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_c_shift_ram_0_4/sim/soc_c_shift_ram_0_4.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_0_5/sim/soc_xlslice_0_5.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_0_5/sim/soc_xlconcat_0_5.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconstant_0_1/sim/soc_xlconstant_0_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_0_6/sim/soc_xlconcat_0_6.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_0_6/sim/soc_xlslice_0_6.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconstant_0_2/sim/soc_xlconstant_0_2.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_0_7/sim/soc_xlconcat_0_7.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_reduced_logic_1_0/sim/soc_util_reduced_logic_1_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_1_2/sim/soc_util_vector_logic_1_2.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlslice_7_0/sim/soc_xlslice_7_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_1_3/sim/soc_util_vector_logic_1_3.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconstant_0_3/sim/soc_xlconstant_0_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_axi_bram_ctrl_1_0/sim/soc_axi_bram_ctrl_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_bram_ctrl_2_bram_0/sim/soc_axi_bram_ctrl_2_bram_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_0_8/sim/soc_xlconcat_0_8.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_c_counter_binary_0_3/sim/soc_c_counter_binary_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/571c/hdl/verilog" +incdir+"$ref_dir/../../../../bram_comm_2.srcs/sources_1/bd/soc/ipshared/5123" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_1_4/sim/soc_util_vector_logic_1_4.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_0_9/sim/soc_util_vector_logic_0_9.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.soc xil_defaultlib.glbl -o soc_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./soc_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./soc.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key soc_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc soc_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./soc.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: soc.sh [-help]\n\
Usage: soc.sh [-lib_map_path]\n\
Usage: soc.sh [-reset_run]\n\
Usage: soc.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
