# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dell_/Documents/vivado_zncc/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_c_shift_ram_0_8/soc_c_shift_ram_0_8.xci
# IP: The module: 'soc_c_shift_ram_0_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell_/Documents/vivado_zncc/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_c_shift_ram_0_8/soc_c_shift_ram_0_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_c_shift_ram_0_8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/dell_/Documents/vivado_zncc/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_c_shift_ram_0_8/soc_c_shift_ram_0_8.xci
# IP: The module: 'soc_c_shift_ram_0_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell_/Documents/vivado_zncc/bram_comm_2/bram_comm_2.srcs/sources_1/bd/soc/ip/soc_c_shift_ram_0_8/soc_c_shift_ram_0_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_c_shift_ram_0_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
